#cloud-config

users:
- name: {username}
  sudo: ['ALL=(ALL) NOPASSWD:ALL']
  groups: sudo
  shell: /bin/bash
  passwd: {password}
  lock_passwd: false

ssh_pwauth: true

write_files:
- encoding: b64
  content: {file-content}
  path: /home/{username}/tgs.zip
  permissions: '0644'

packages:
- unzip
- python-is-python3
- python3-pip

runcmd:
- [ chown, -R, {username}:{username}, /home/{username} ]
- [ su, -, {username}, -c, "mkdir -p tgs && unzip -o tgs.zip -d tgs" ]
- [ su, -, {username}, -c, "pip3 install -r tgs/requirements.txt" ]
- [ su, -, {username}, -c, "python tgs/tgs_rest_api.py > /tmp/tgs_start.log 2>&1 &" ]
