#cloud-config

users:
- name: cisco
  sudo: ['ALL=(ALL) NOPASSWD:ALL']
  groups: sudo
  shell: /bin/bash

ssh_pwauth: true

chpasswd:
  list: |
    cisco:cisco
  expire: false

write_files:
- encoding: b64
  content: {file-content}
  path: /home/cisco/tgs.zip
  permissions: '0644'

packages:
- unzip
- python-is-python3
- python3-pip

runcmd:
- [ chown, -R, cisco:cisco, /home/cisco ]
- [ su, -, cisco, -c, "mkdir -p tgs && unzip -o tgs.zip -d tgs" ]
- [ su, -, cisco, -c, "pip3 install -r tgs/requirements.txt" ]
- [ su, -, cisco, -c, "python tgs/tgs_rest_api.py > /tmp/tgs_start.log 2>&1 &" ]
